/* ═══════════════════════════════════════════════
   AARTI — SHARED COMMON JS
   Used by all pages
═══════════════════════════════════════════════ */

// ── FIREBASE ──
const firebaseConfig={apiKey:"AIzaSyBv-NSwb78D-dbWGWOBVp-d8ZV9BXZbg80",authDomain:"aarti-7246c.firebaseapp.com",projectId:"aarti-7246c",storageBucket:"aarti-7246c.firebasestorage.app",messagingSenderId:"73572412831",appId:"1:73572412831:web:65d183b26bc7ba96be21aa"};
let _firestore=null,_usingFirebase=false;
try{firebase.initializeApp(firebaseConfig);_firestore=firebase.firestore();_usingFirebase=true;}catch(e){console.warn("Firebase:",e.message);}

// ── SHARED STORAGE ──
window.storage={
  get:async(k)=>{if(_usingFirebase&&_firestore){try{const d=await _firestore.collection("aarti_business").doc(k).get();return d.exists?{value:d.data().value}:null;}catch(e){return null;}}const v=localStorage.getItem("aarti_"+k);return v?{value:v}:null;},
  set:async(k,v)=>{if(_usingFirebase&&_firestore){try{await _firestore.collection("aarti_business").doc(k).set({value:v});return{key:k,value:v};}catch(e){return null;}}localStorage.setItem("aarti_"+k,v);return{key:k,value:v};}
};

// ── CUSTOMER AUTH ──
const CUSTOMERS_COL="aarti_customers";
let _loggedInUser=null;
async function registerCustomer(name,email,phone,password){if(!_firestore)return{ok:false,msg:"Firebase not connected"};try{const ex=await _firestore.collection(CUSTOMERS_COL).where("email","==",email).get();if(!ex.empty)return{ok:false,msg:"Email already registered"};const id=Date.now().toString(36)+Math.random().toString(36).slice(2);await _firestore.collection(CUSTOMERS_COL).doc(id).set({id,name,email,phone,password:btoa(password),added:new Date().toISOString().slice(0,10),orders:0,spent:0,status:"active"});_loggedInUser={id,name,email,phone};localStorage.setItem("aarti_user",JSON.stringify(_loggedInUser));return{ok:true};}catch(e){return{ok:false,msg:e.message};}}
async function loginCustomer(email,password){if(!_firestore)return{ok:false,msg:"Firebase not connected"};try{const snap=await _firestore.collection(CUSTOMERS_COL).where("email","==",email).get();if(snap.empty)return{ok:false,msg:"Email not found"};const user=snap.docs[0].data();if(atob(user.password)!==password)return{ok:false,msg:"Wrong password"};_loggedInUser={id:user.id,name:user.name,email:user.email,phone:user.phone};localStorage.setItem("aarti_user",JSON.stringify(_loggedInUser));return{ok:true,user:_loggedInUser};}catch(e){return{ok:false,msg:e.message};}}
function logoutCustomer(){_loggedInUser=null;localStorage.removeItem("aarti_user");updateNavUser();}
function loadLoggedInUser(){const s=localStorage.getItem("aarti_user");if(s){try{_loggedInUser=JSON.parse(s);}catch(e){}}}
function updateNavUser(){const btn=document.getElementById("nav-user-btn");if(!btn)return;if(_loggedInUser){btn.innerHTML=`👤 ${_loggedInUser.name.split(" ")[0]}`;btn.onclick=()=>{location.href='account.html'};}else{btn.innerHTML="👤";btn.onclick=()=>{location.href='auth.html'};}}

// ── SHARED DB ──
let PRODS=[],CATS=[],SETTINGS={};
async function loadSharedDB(){try{const r=await window.storage.get('aarti-db');if(r&&r.value){const d=JSON.parse(r.value);PRODS=d.products||[];CATS=d.categories||[];SETTINGS=d.settings||{};}}catch(e){}
if(!PRODS.length){CATS=[{id:'c1',name:'Agarbatti',emoji:'🌸'},{id:'c2',name:'Copper Idols',emoji:'🏺'},{id:'c3',name:'Handmade Candles',emoji:'🕯️'},{id:'c4',name:'Dhoop',emoji:'🌿'},{id:'c5',name:'Pooja Thali',emoji:'🪷'},{id:'c6',name:'Pooja Items',emoji:'🛕'}];PRODS=[{id:'p1',name:'Sandalwood Agarbatti',cat:'c1',emoji:'🌸',price:299,oldPrice:399,stock:847,sku:'ART-AGB-001',desc:'Premium sandalwood incense sticks, 40 sticks per pack.',status:'active',imgUrl:'',imgData:''},{id:'p2',name:'Copper Ganesha Idol',cat:'c2',emoji:'🏺',price:1849,oldPrice:2499,stock:23,sku:'ART-IDL-001',desc:'Beautifully handcrafted pure copper Ganesha idol, 6 inches.',status:'active',imgUrl:'',imgData:''},{id:'p3',name:'Beeswax Temple Candle Set',cat:'c3',emoji:'🕯️',price:649,oldPrice:849,stock:185,sku:'ART-CND-001',desc:'Pure beeswax candles in sacred shapes. Set of 6.',status:'active',imgUrl:'',imgData:''},{id:'p4',name:'Rose Dhoop Cones',cat:'c4',emoji:'🌹',price:199,oldPrice:249,stock:120,sku:'ART-DHP-001',desc:'Natural dhoop cones infused with real rose petals. 20 per pack.',status:'active',imgUrl:'',imgData:''},{id:'p5',name:'Brass Pooja Thali Set',cat:'c5',emoji:'🪷',price:2249,oldPrice:2999,stock:54,sku:'ART-THI-001',desc:'Complete 7-piece brass pooja thali for daily rituals.',status:'active',imgUrl:'',imgData:''},{id:'p6',name:'Sacred Copper Diya Set',cat:'c6',emoji:'🪔',price:649,oldPrice:899,stock:210,sku:'ART-DYA-001',desc:'Pure copper diya set crafted in Vrindavan. Set of 5.',status:'active',imgUrl:'',imgData:''},{id:'p7',name:'Nag Champa Agarbatti',cat:'c1',emoji:'💜',price:349,oldPrice:449,stock:640,sku:'ART-AGB-002',desc:'Iconic Nag Champa blend with premium champa flowers. 50 sticks.',status:'active',imgUrl:'',imgData:''},{id:'p8',name:'Havan Samagri Premium',cat:'c6',emoji:'🌾',price:399,oldPrice:499,stock:300,sku:'ART-HVN-001',desc:'Pure havan samagri with 108 natural herbs and woods.',status:'active',imgUrl:'',imgData:''}];}
applySettings();}
function applySettings(){const s=SETTINGS;const waNum=(s.whatsapp||'+91 9876543210').replace(/\D/g,'');const waLink=`https://wa.me/${waNum}?text=Hello!%20I%20want%20to%20order%20from%20Aarti`;const waFloat=document.getElementById('wa-float');const waTopbar=document.getElementById('wa-topbar');if(waFloat)waFloat.href=waLink;if(waTopbar)waTopbar.textContent='📞 Call: '+(s.whatsapp||'+91 98765 43210');const cEmail=document.getElementById('c-email');const cPhone=document.getElementById('c-phone');if(cEmail&&s.email)cEmail.textContent=s.email;if(cPhone&&s.whatsapp)cPhone.textContent=s.whatsapp;}

// ── CART ──
let cart=[];
function loadCart(){try{cart=JSON.parse(localStorage.getItem('aarti_cart')||'[]');}catch(e){cart=[];}}
function saveCart(){localStorage.setItem('aarti_cart',JSON.stringify(cart));}
function addToCart(id){const p=PRODS.find(x=>x.id===id);if(!p)return;const e=cart.find(c=>c.id===id);if(e)e.qty++;else cart.push({...p,qty:1});saveCart();updCartBadge();toast2(`✓ ${p.name} added!`,'success');}
function updCartBadge(){const t=cart.reduce((s,c)=>s+c.qty,0);const b=document.getElementById('cart-badge');if(b)b.textContent=t;}

// ── WISHLIST ──
let wishlist=[];
function loadWishlist(){try{wishlist=JSON.parse(localStorage.getItem('aarti_wl')||'[]');}catch(e){wishlist=[];}}
function saveWishlist(){localStorage.setItem('aarti_wl',JSON.stringify(wishlist));const wc=document.getElementById('wl-count');if(wc)wc.textContent=wishlist.length;}
function toggleWl(id,btn){const p=PRODS.find(x=>x.id===id);if(!p)return;const idx=wishlist.findIndex(w=>w.id===id);if(idx>-1){wishlist.splice(idx,1);btn.classList.remove('act');toast2('Removed from wishlist');}else{wishlist.push(p);btn.classList.add('act');toast2('♡ '+p.name+' saved to wishlist','success');}saveWishlist();}

// ── UTILS ──
function esc(s){return String(s||'').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
let toastT;
function toast2(msg,type=''){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.className='toast '+(type||'')+' show';clearTimeout(toastT);toastT=setTimeout(()=>t.classList.remove('show'),3200);}
function getCatName(id){const c=CATS.find(x=>x.id===id);return c?c.name:'—';}
function handleNL(e){e.preventDefault();toast2('✓ Subscribed to our newsletter!','success');e.target.reset();}

// ── PRODUCT CARD ──
function prodCard(p){const src=p.imgUrl||p.imgData||'';const disc=p.oldPrice&&+p.oldPrice>+p.price?Math.round((1-p.price/p.oldPrice)*100):0;const inWl=wishlist.some(w=>w.id===p.id);const badge=p.badge?`<span class="pbadge pbadge-${p.badge}">${p.badge==='bestseller'?'⭐ Bestseller':p.badge.charAt(0).toUpperCase()+p.badge.slice(1)}</span>`:'';const imgContent=src?`<img src="${src}" style="width:100%;height:100%;object-fit:cover" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'"><div class="prod-img-emoji" style="display:none">${p.emoji||'📦'}</div>`:`<div class="prod-img-emoji">${p.emoji||'📦'}</div>`;return`<div class="prod-card" onclick="showProd('${p.id}')"><div class="prod-img-wrap">${imgContent}<div class="prod-badges">${badge}</div><button class="prod-wish ${inWl?'act':''}" onclick="event.stopPropagation();toggleWl('${p.id}',this)">♡</button></div><div class="prod-info"><div class="prod-brand">Aarti</div><div class="prod-name">${esc(p.name)}</div><div class="prod-rating"><div class="stars" id="prating-${p.id}">★★★★★</div><div class="rnum" id="prcount-${p.id}"></div></div><div class="prod-price-row"><div class="price">₹${(+p.price).toLocaleString('en-IN')}</div>${p.oldPrice?`<div class="price-old">₹${(+p.oldPrice).toLocaleString('en-IN')}</div><div class="price-off">${disc}% off</div>`:''}</div><button class="btn-add" onclick="event.stopPropagation();addToCart('${p.id}')">🛒 Add to Cart</button></div></div>`;}
function showProd(id){localStorage.setItem('aarti_cur_prod',id);location.href='product.html';}

// ── RATINGS ──
const RATINGS_COL='aarti_ratings';
let _selectedStars=0;
const _ratingCache={};
async function loadRatings(pid){if(!_firestore)return[];try{const snap=await _firestore.collection(RATINGS_COL).where('productId','==',pid).get();const docs=snap.docs.map(d=>d.data());docs.sort((a,b)=>(b.date||'').localeCompare(a.date||''));return docs;}catch(e){return[];}}
async function submitRating(pid,stars,comment){if(!_loggedInUser){toast2('Please sign in to write a review','error');location.href='auth.html';return;}if(!_firestore){toast2('Firebase not connected','error');return;}const btn=document.querySelector('#write-review-area button');if(btn){btn.disabled=true;btn.textContent='Saving…';}const docId=pid+'_'+_loggedInUser.id;try{await _firestore.collection(RATINGS_COL).doc(docId).set({productId:pid,stars,comment:comment||'',userId:_loggedInUser.id,userName:_loggedInUser.name,date:new Date().toISOString().slice(0,10)});delete _ratingCache[pid];toast2('✓ Review saved! Other customers can now see it.','success');await renderRatings(pid);}catch(e){toast2('✕ Could not save: '+e.message,'error');if(btn){btn.disabled=false;btn.textContent='Submit Review ✦';}}}
function selectStar(n){_selectedStars=n;document.querySelectorAll('#star-input-row span').forEach((s,i)=>s.classList.toggle('lit',i<n));}
async function handleSubmitRating(pid){if(!_selectedStars){toast2('Please tap a star to rate','error');return;}const c=(document.getElementById('review-comment')||{}).value||'';await submitRating(pid,_selectedStars,c.trim());}
function starsHtml(n){const f=Math.round(n);return'★'.repeat(f)+'☆'.repeat(5-f);}
async function renderRatings(pid){const ratings=await loadRatings(pid);const avg=ratings.length?(ratings.reduce((s,r)=>s+r.stars,0)/ratings.length):0;const detStars=document.getElementById('det-stars');const detCount=document.getElementById('det-rcount');if(detStars){detStars.textContent=starsHtml(avg||5);detStars.style.color='var(--gold)';}if(detCount)detCount.textContent=ratings.length?`(${ratings.length} review${ratings.length>1?'s':''})`:'(No reviews yet)';const avgEl=document.getElementById('avg-rating-display');if(avgEl)avgEl.innerHTML=ratings.length?`<div class="avg-rating-block"><div><div class="avg-num">${avg.toFixed(1)}</div><div class="avg-stars-big">${starsHtml(avg)}</div></div><div><div class="avg-count">${ratings.length} review${ratings.length>1?'s':''}</div></div></div>`:`<p style="color:var(--t3);font-size:.85rem;margin-bottom:1rem">No reviews yet — be the first!</p>`;const writeEl=document.getElementById('write-review-area');if(writeEl){if(_loggedInUser){_selectedStars=0;writeEl.innerHTML=`<div class="write-review-box"><div style="font-weight:700;font-size:.9rem;color:var(--maroon);margin-bottom:.3rem">✍️ Write a Review</div><div style="font-size:.78rem;color:var(--t3);margin-bottom:.1rem">Tap stars to rate:</div><div class="star-input" id="star-input-row"><span onclick="selectStar(1)">★</span><span onclick="selectStar(2)">★</span><span onclick="selectStar(3)">★</span><span onclick="selectStar(4)">★</span><span onclick="selectStar(5)">★</span></div><textarea id="review-comment" class="form-input" rows="3" placeholder="Share your experience…" style="margin-bottom:.75rem;font-size:.85rem;resize:vertical"></textarea><button class="btn-primary" style="font-size:.82rem;padding:.65rem 1.6rem" onclick="handleSubmitRating('${pid}')">Submit Review ✦</button></div>`;}else{writeEl.innerHTML=`<div style="background:var(--cream);border:1px solid var(--border);border-radius:10px;padding:1rem 1.25rem;margin-bottom:1.25rem;font-size:.85rem;color:var(--t2)"><a style="color:var(--saffron);cursor:pointer;font-weight:700" href="auth.html">Sign in</a> to write a review.</div>`;}}const listEl=document.getElementById('reviews-list');if(listEl)listEl.innerHTML=ratings.length?ratings.map(r=>`<div class="review-card"><div class="review-header"><div class="review-av">${esc(r.userName.charAt(0).toUpperCase())}</div><div><div class="review-name">${esc(r.userName)}</div><div class="review-date">${r.date||''}</div></div><div class="review-stars-sm">${'★'.repeat(r.stars)}${'☆'.repeat(5-r.stars)}</div></div>${r.comment?`<div class="review-text">"${esc(r.comment)}"</div>`:''}</div>`).join(''):'';}
async function loadCardRatings(ids){if(!_firestore||!ids.length){ids.forEach(id=>{const s=document.getElementById('prating-'+id);if(s)s.textContent='★★★★★';});return;}for(const id of ids){if(_ratingCache[id]){_applyCardRating(id,_ratingCache[id].avg,_ratingCache[id].count);continue;}_firestore.collection(RATINGS_COL).where('productId','==',id).get().then(snap=>{const count=snap.size;const avg=count?(snap.docs.reduce((s,d)=>s+d.data().stars,0)/count):0;_ratingCache[id]={avg,count};_applyCardRating(id,avg,count);}).catch(()=>_applyCardRating(id,5,0));}}
function _applyCardRating(id,avg,count){const s=document.getElementById('prating-'+id);const c=document.getElementById('prcount-'+id);if(s)s.textContent=starsHtml(avg||5);if(c)c.textContent=count?`(${count})`:'';} 

// ── FOOTER CATS ──
function renderFooterCats(){const fc=document.getElementById('footer-cats');if(fc)fc.innerHTML=CATS.slice(0,5).map(c=>`<li><a href="shop.html">${c.emoji} ${esc(c.name)}</a></li>`).join('');}
